---
version: 2
project_name: cf-alias

builds:
  - id: cf-alias
    main: ./tools/goreleaser.go
    goos:
      - linux
    goarch:
      - amd64
    builder: go
    hooks:
      post:
        - ./tools/goreleaser-dist.sh {{ .Target }}
        - ./tools/aur-push.sh

checksum:
  name_template: checksums.txt

snapshot:
  version_template: '{{ .Tag }}-next'

archives:
  - formats:
      - tar.gz
    files:
      - LICENSE
      - completions/cf-alias.bash
      - completions/_cf-alias
      - completions/cf-alias.fish

signs:
  - artifacts: checksum
    args:
      - -u
      - A81FA5D0033F6EACD61808CD426D822F91067068
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

nfpms:
  - homepage: https://github.com/4ndr0666/cf-alias
    description: >
      Create Cloudflare email alias' directly from your terminal or Alfred.
    maintainer: 4ndr0666
    vendor: 4ndr0666
    formats:
      - deb
      - rpm
    contents:
      - src: ./completions/cf-alias.bash
        dst: /usr/share/bash-completion/completions/cf-alias
        file_info:
          mode: 420
      - src: ./completions/_cf-alias
        dst: /usr/share/zsh/site-functions/_cf-alias
        file_info:
          mode: 420
      - src: ./completions/cf-alias.fish
        dst: /usr/share/fish/vendor_completions.d/cf-alias.fish
        file_info:
          mode: 420
      - src: ./LICENSE
        dst: /usr/share/doc/cf-alias/LICENSE
        file_info:
          mode: 420

aurs:
  - name: cf-alias-bin
    homepage: https://github.com/4ndr0666/cf-alias
    description: >
      Create Cloudflare email alias' directly from your terminal or Alfred
    maintainers:
      - 4ndr0666
    contributors:
      - 4ndr0666
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/cf-alias-bin.git

    package: |
      install -Dm755 "./cf-alias" \
        "${pkgdir}/usr/bin/cf-alias"
      install -Dm644 "./LICENSE" \
        "${pkgdir}/usr/share/licenses/cf-alias/LICENSE"
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/cf-alias.bash" \
        "${pkgdir}/usr/share/bash-completion/completions/cf-alias"
      install -Dm644 "./completions/_cf-alias" \
        "${pkgdir}/usr/share/zsh/site-functions/_cf-alias"
      install -Dm644 "./completions/cf-alias.fish" \
        "${pkgdir}/usr/share/fish/vendor_completions.d/cf-alias.fish"

changelog:
  use: git

release:
  github:
    owner: 4ndr0666
    name: cf-alias
  prerelease: false
  draft: false
  replace_existing_draft: true
    overwrite: true
  footer: |
    Built and published by GoReleaser on {{ .Date }} (commit {{ .FullCommit }}).
