---
project_name: cf-alias

builds:
  - main: ./tools/goreleaser.go
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post: ./tools/goreleaser-dist.sh {{ .Target }}

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

archives:
  - format: tar.gz
    files:
      - LICENSE
      - THIRDPARTY.json

signs:
  - artifacts: checksum
    args:
      [
        "-u",
        "A81FA5D0033F6EACD61808CD426D822F91067068",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}"
      ]

nfpms:
  - homepage: https://github.com/4ndr0666/cf-alias
    description: >
      Create Cloudflare email aliases directly from your terminal or Alfred.
    maintainer: 4ndr0666
    vendor: 4ndr0666
    formats:
      - deb
      - rpm
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/cf-alias/LICENSE
        file_info:
          mode: 0644
      - src: ./THIRDPARTY.json
        dst: /usr/share/doc/cf-alias/THIRDPARTY.json
        file_info:
          mode: 0644

aurs:
  - name: cf-alias-bin
    homepage: https://github.com/4ndr0666/cf-alias
    description: >
      Create Cloudflare email aliases directly from your terminal or Alfred.
    maintainers: ["4ndr0666"]
    contributors: ["4ndr0666"]
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/cf-alias-bin.git
    package: |-
      install -Dm755 "./cf-alias" \
        "${pkgdir}/usr/bin/cf-alias"
      install -Dm644 "./LICENSE" \
        "${pkgdir}/usr/share/licenses/cf-alias/LICENSE"
      install -Dm644 "./THIRDPARTY.json" \
        "${pkgdir}/usr/share/licenses/cf-alias/THIRDPARTY.json"

changelog:
  use: github-native
