name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build binary
        run: cargo build --release

      - name: Run tests
        run: cargo test --release --locked

      - name: Generate license manifest
        run: |
          cargo install cargo-about --force
          cargo about generate --format json > THIRDPARTY.json

      - name: Archive artifacts
        run: |
          mkdir -p dist
          cp target/release/cf-alias dist/
          cp LICENSE THIRDPARTY.json dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cf-alias-binaries
          path: dist/

  aur-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          GPG_FINGERPRINT: A81FA5D0033F6EACD61808CD426D822F91067068
